export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const SELLER_REPOSITORY = Symbol('SELLER_REPOSITORY');
export const SHOP_REPOSITORY = Symbol('SHOP_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const POST_REPOSITORY = Symbol('POST_REPOSITORY');
export const COLLECTION_REPOSITORY = Symbol('COLLECTION_REPOSITORY');
export const OUTFIT_REPOSITORY = Symbol('OUTFIT_REPOSITORY');
export const EVENT_REPOSITORY = Symbol('EVENT_REPOSITORY');
export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const PROMOTION_REPOSITORY = Symbol('PROMOTION_REPOSITORY');

