export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const SELLER_REPOSITORY = Symbol('SELLER_REPOSITORY');
export const SHOP_REPOSITORY = Symbol('SHOP_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');

